#!/usr/bin/env python3
"""Create and verify concise hash locks from a target-specific wheel directory."""

from __future__ import annotations

import argparse
import email.parser
import hashlib
import json
import pathlib
import re
import zipfile


LOCK_RE = re.compile(
    r"^(?P<name>[a-z0-9][a-z0-9._-]*)==(?P<version>[^ ]+) "
    r"--hash=sha256:(?P<digest>[0-9a-f]{64})$"
)


class WheelhouseError(ValueError):
    """A wheelhouse cannot be represented by or does not match its lock."""


def canonical_name(value: str) -> str:
    return re.sub(r"[-_.]+", "-", value).lower()


def wheel_identity(path: pathlib.Path) -> tuple[str, str]:
    try:
        with zipfile.ZipFile(path) as archive:
            metadata_names = [
                name for name in archive.namelist()
                if name.endswith(".dist-info/METADATA")
            ]
            if len(metadata_names) != 1:
                raise WheelhouseError(f"{path.name} does not contain exactly one METADATA file")
            metadata = email.parser.Parser().parsestr(
                archive.read(metadata_names[0]).decode("utf-8")
            )
    except (OSError, UnicodeDecodeError, zipfile.BadZipFile) as exc:
        raise WheelhouseError(f"unreadable wheel {path.name}: {exc}") from exc
    name = metadata.get("Name")
    version = metadata.get("Version")
    if not name or not version or any(character.isspace() for character in version):
        raise WheelhouseError(f"{path.name} has invalid package metadata")
    return canonical_name(name), version


def wheel_records(directory: pathlib.Path) -> dict[str, dict[str, str]]:
    if not directory.is_dir():
        raise WheelhouseError(f"wheel directory is missing: {directory}")
    records: dict[str, dict[str, str]] = {}
    for path in sorted(directory.glob("*.whl")):
        name, version = wheel_identity(path)
        if name in records:
            raise WheelhouseError(f"multiple wheels supplied for {name}")
        records[name] = {
            "version": version,
            "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
            "file": path.name,
        }
    if not records:
        raise WheelhouseError(f"no wheels found in {directory}")
    return records


def write_lock(directory: pathlib.Path, output: pathlib.Path, target: str) -> dict[str, object]:
    records = wheel_records(directory)
    lines = [
        "# Generated by ASIP wheelhouse lock helper.",
        f"# Target: {target}; binary wheels only.",
        "# Product installs must also use --no-index and --find-links.",
    ]
    for name, record in sorted(records.items()):
        lines.append(
            f"{name}=={record['version']} --hash=sha256:{record['sha256']}"
        )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"schema_version": 1, "target": target, "packages": len(records)}


def read_lock(path: pathlib.Path) -> dict[str, dict[str, str]]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except OSError as exc:
        raise WheelhouseError(f"lock is unreadable: {path}: {exc}") from exc
    records: dict[str, dict[str, str]] = {}
    for line_number, raw in enumerate(lines, 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        match = LOCK_RE.fullmatch(line)
        if not match:
            raise WheelhouseError(f"unsupported lock entry at {path}:{line_number}")
        name = canonical_name(match.group("name"))
        if name in records:
            raise WheelhouseError(f"duplicate lock entry for {name}")
        records[name] = {
            "version": match.group("version"),
            "sha256": match.group("digest"),
        }
    if not records:
        raise WheelhouseError(f"lock contains no packages: {path}")
    return records


def verify(directory: pathlib.Path, lock: pathlib.Path) -> dict[str, object]:
    wheels = wheel_records(directory)
    expected = read_lock(lock)
    missing = sorted(set(expected) - set(wheels))
    extra = sorted(set(wheels) - set(expected))
    mismatched = sorted(
        name for name in set(wheels) & set(expected)
        if wheels[name]["version"] != expected[name]["version"]
        or wheels[name]["sha256"] != expected[name]["sha256"]
    )
    if missing or extra or mismatched:
        raise WheelhouseError(
            "wheelhouse mismatch: missing=%s extra=%s mismatched=%s" %
            (missing, extra, mismatched)
        )
    return {
        "schema_version": 1,
        "status": "pass",
        "packages": len(wheels),
        "lock": str(lock),
        "wheelhouse": str(directory),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="action", required=True)
    create = subparsers.add_parser("create")
    create.add_argument("directory", type=pathlib.Path)
    create.add_argument("output", type=pathlib.Path)
    create.add_argument("--target", required=True)
    check = subparsers.add_parser("verify")
    check.add_argument("directory", type=pathlib.Path)
    check.add_argument("lock", type=pathlib.Path)
    args = parser.parse_args(argv)
    try:
        result = (
            write_lock(args.directory, args.output, args.target)
            if args.action == "create" else verify(args.directory, args.lock)
        )
    except WheelhouseError as exc:
        parser.error(str(exc))
    print(json.dumps(result, separators=(",", ":"), sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
